version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped

  celery-worker:
    build: .
    env_file: .env
    command: celery -A celery_app.app worker -l info
    volumes:
      - ./data:/data
    depends_on:
      - redis
    restart: unless-stopped

  celery-beat:
    build: .
    env_file:
      - .env
    command: celery -A celery_app.app beat -l info
    volumes:
      - ./data:/data
    depends_on:
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - data:/data

      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  data:

